# Generated by Django 4.2.5 on 2023-11-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="service_coverimage",
            new_name="coverimage",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="service_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="service_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="service_summery",
            new_name="summery",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="service_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="icon",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
