# Generated by Django 4.2.5 on 2023-11-02 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_rename_service_coverimage_service_coverimage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="coverimage",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="service",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="service",
            name="summery",
        ),
    ]
