# Generated by Django 4.2.5 on 2023-11-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_rename_coverimage_service_image_remove_service_icon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
    ]
