# Generated by Django 4.2.7 on 2023-11-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'ServiceCategories'},
        ),
        migrations.AlterModelOptions(
            name='serviceenquiry',
            options={'verbose_name_plural': 'ServiceEnquiries'},
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='icon',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
    ]
