# Generated by Django 4.2.5 on 2023-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
            ],
        ),
    ]
