# Generated by Django 4.2.5 on 2023-11-09 10:24

from django.db import migrations, models
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_alter_servicecategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="banner"),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="client"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
