# Generated by Django 4.2.5 on 2023-11-02 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_serviceenquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceenquiry",
            name="service",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="web.service"
            ),
            preserve_default=False,
        ),
    ]
