# Generated by Django 4.2.5 on 2023-11-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_banner_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="description",
            field=models.TextField(),
        ),
    ]
