# Generated by Django 4.2.5 on 2023-11-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_serviceenquiry_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
