# Generated by Django 4.2.5 on 2023-11-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_banner_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="order",
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
