# Generated by Django 4.2.5 on 2023-11-09 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_client_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("order",),
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
