# Generated by Django 4.2.5 on 2023-11-03 04:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="update",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
