# Generated by Django 4.2.5 on 2023-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_service_description_alter_update_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("file", models.FileField(upload_to="career")),
            ],
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="service"),
        ),
        migrations.AlterField(
            model_name="update",
            name="image",
            field=models.ImageField(upload_to="update"),
        ),
    ]
