# Generated by Django 4.2.5 on 2023-11-03 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_career_alter_service_image_alter_update_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="career",
            old_name="file",
            new_name="cv",
        ),
    ]
