# Generated by Django 4.2.5 on 2023-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_rename_file_career_cv"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project")),
                ("title", models.CharField(max_length=100)),
            ],
        ),
    ]
